#Prefix for API
WARD_API_PREFIX = "/ward"
INMATE_API_PREFIX = "/inmate"
DOCTOR_API_PREFIX = "/doctor"
BED_API_PREFIX = "/bed"
ENV_DATA_API_PREFIX = "/env_data"
ROOM_API_PREFIX = "/room"
VITAL_DATA_API_PREFIX = "/vital_data"
EMERGENCY_API_PREFIX = "/emergency"